### ISSUE TITLE
Theme Variations and Customizable Accent Color

### ISSUE THREAD

**Issue by vioo-bkp** [seppzer0/silent-writing-theme#3]
I just found your theme, and I was blew away seeing such a nice monochrome theme!!

So I want to suggest some good features that can improve overall this idea of silent-writing!
- Offer variations on the theme with slight modifications, such as a "dark gray" or "warm white" version, to cater to different tastes;
- Set a custom accent color for highlights, errors, or special keywords, which would add a pop of color to the otherwise monochromatic theme.

**Comment by seppzer0** [comment]
It is always nice knowing there is somebody who likes the same things you do :)
<br>
> variations on the theme with slight modifications, such as a "dark gray" or "warm white" version, to cater to different tastes

I have thought of that a little while back, and I do have a few ideas of alternative colour schemes in mind.

They will probably be shifted from a "black & white" to "dark & warm" colour pallete. It technically breaks the monochrome aesthetic, but I do think that I'll eventually add them -- I feel like they would be a good addition for those moments when you want something a bit more than just black and white.
<br>

> a custom accent color for highlights, errors, or special keywords, which would add a pop of color to the otherwise monochromatic theme

It depends on what you mean exactly here.

The main idea of this theme is to make text look as simple as possible, similar to how it does in terminals. I don't really want to alternate the colour of text (e.g., for comments, docstrings or other syntax-related elements), but if you're talking about UI elements outside of that scope, then I would probably look into it.

I personally don't always use all the functionality of VSCode in my workflow, so I might miss some of the elements that are apparent to others.

In that case, if you already have any ideas -- a PR is welcome! I will likely reach those missed elements in time myself, but if somebody else does before me, it would be even better.

<br>
In any case, thank you for your suggestions! I do appreciate the feedback.

**Comment by seppzer0** [comment]
I've [updated](https://github.com/seppzer0/silent-writing-theme/releases/tag/v0.3.0) a few UI colours in the theme, should look a bit better now.
Again, with time all the nuances will be covered eventually, I plan to keep updating them periodically.

As for this issue -- I will close it for now. I'll keep in mind all the notes mentioned here, and if you have any new issues with the theme -- feel free to open a new ticket.

Thanks again for the feedback!
